# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
- name: buildpool
  displayName: Agent Pool
  type: string
  default: Azure Pipelines (windows-latest)
  values:
  - Azure Pipelines (windows-latest)
  - Self-Hosted Windows Clients

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - 'development'
    - 'master'

jobs:
- job: 'Build'
  pool:
    ${{ if eq(parameters.buildpool, 'Azure Pipelines (windows-latest)') }}:
      vmImage: 'windows-latest'
    ${{ if eq(parameters.buildpool, 'Self-Hosted Windows Clients') }}:
      name: Self-Hosted Windows Clients

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**\*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\Package'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\Package'
